#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.8"
# dependencies = []
# ///
# gingugu-init:managed-file - regenerated by `gingugu harness`; local edits are lost on --force
"""Event logger - appends one JSON line of metadata per hook event.

Reads the event payload on stdin and appends what happened - never the content
- plus a ``logged_at`` timestamp, to ``<project>/logs/<event_in_snake_case>.jsonl``.
The project is ``$CLAUDE_PROJECT_DIR``, falling back to the current directory.

Payloads carry file bodies, command output, prompts and form answers, any of
which can hold a secret. So only the scalar fields in ``KEEP`` are logged, and
``tool_input`` is cut down to the path it touched.

Installed by `gingugu harness`. Pure stdlib. Never fails the session: any
problem (bad payload, unwritable disk) exits 0 with no output.
"""

import json
import os
import re
import sys
from datetime import datetime

KEEP = (
    "hook_event_name",
    "session_id",
    "cwd",
    "permission_mode",
    "tool_name",
    "tool_use_id",
    "agent_id",
    "agent_type",
    "source",
    "trigger",
    "reason",
    "notification_type",
    "file_path",
    "is_interrupt",
    "stop_hook_active",
    "mcp_server_name",
)
TOOL_INPUT_KEEP = ("file_path", "path", "notebook_path")


def snake_case(name: str) -> str:
    """PostToolUse -> post_tool_use."""
    return re.sub(r"(?<!^)(?=[A-Z])", "_", name).lower()


def _scalar(value) -> bool:
    return value is None or isinstance(value, (str, int, float, bool))


def metadata(data: dict) -> dict:
    """The loggable part of a payload: allowlisted scalars and the tool's path."""
    entry = {key: data[key] for key in KEEP if key in data and _scalar(data[key])}
    tool_input = data.get("tool_input")
    if isinstance(tool_input, dict):
        paths = {k: tool_input[k] for k in TOOL_INPUT_KEEP if isinstance(tool_input.get(k), str)}
        if paths:
            entry["tool_input"] = paths
    entry["logged_at"] = datetime.now().isoformat()
    return entry


def main() -> None:
    try:
        data = json.loads(sys.stdin.read())
        if not isinstance(data, dict):
            return
        event = snake_case(str(data.get("hook_event_name") or "unknown"))
        event = re.sub(r"[^a-z0-9_]", "", event) or "unknown"
        project = os.environ.get("CLAUDE_PROJECT_DIR") or os.getcwd()
        log_dir = os.path.join(project, "logs")
        os.makedirs(log_dir, exist_ok=True)
        with open(os.path.join(log_dir, f"{event}.jsonl"), "a") as handle:
            handle.write(json.dumps(metadata(data)) + "\n")
    except Exception:
        pass


if __name__ == "__main__":
    main()
    sys.exit(0)
