#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.8"
# dependencies = []
# ///
# gingugu-init:managed-file - regenerated by `gingugu harness`; local edits are lost on --force
"""PreCompact hook - log the event and, with --backup, keep the transcript.

Compaction rewrites the conversation, so the full transcript is copied first to
``<project>/.claude/data/transcript_backups/<session>_pre_compact_<trigger>_<timestamp>.jsonl``.
That copy holds the whole session - everything it read - so it lives under
``.claude/data/`` (git-ignored by `gingugu init`), owner-only (0700 dir, 0600
file). The event itself, metadata only, goes to ``<project>/logs/pre_compact.jsonl``.
The project is ``$CLAUDE_PROJECT_DIR``, falling back to the current directory.

Installed by `gingugu harness`. Pure stdlib. Always exits 0: a failed backup
must never block compaction.
"""

import argparse
import json
import os
import re
import shutil
import sys
from datetime import datetime
from pathlib import Path


def project_dir() -> Path:
    return Path(os.environ.get("CLAUDE_PROJECT_DIR") or os.getcwd())


def log_pre_compact(input_data: dict, backup_path) -> None:
    """Append the event's metadata as one JSON line - never the transcript itself."""
    entry = {
        "session_id": input_data.get("session_id"),
        "trigger": input_data.get("trigger"),
        "backup": backup_path,
        "logged_at": datetime.now().isoformat(),
    }
    log_dir = project_dir() / "logs"
    log_dir.mkdir(parents=True, exist_ok=True)
    with open(log_dir / "pre_compact.jsonl", "a") as handle:
        handle.write(json.dumps(entry) + "\n")


def backup_transcript(transcript_path, trigger):
    """Copy the transcript aside before compaction; None when there is nothing to copy."""
    try:
        if not os.path.exists(transcript_path):
            return None
        backup_dir = project_dir() / ".claude" / "data" / "transcript_backups"
        backup_dir.mkdir(parents=True, exist_ok=True)
        os.chmod(backup_dir, 0o700)
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        session_name = re.sub(r"[^\w.-]", "_", Path(transcript_path).stem)
        trigger = re.sub(r"[^\w-]", "_", trigger)
        backup_path = backup_dir / f"{session_name}_pre_compact_{trigger}_{timestamp}.jsonl"
        shutil.copyfile(transcript_path, backup_path)
        os.chmod(backup_path, 0o600)
        return str(backup_path)
    except Exception:
        return None


def main() -> None:
    try:
        parser = argparse.ArgumentParser()
        parser.add_argument(
            "--backup", action="store_true", help="Copy the transcript before compaction"
        )
        parser.add_argument("--verbose", action="store_true", help="Print what happened")
        args = parser.parse_args()

        input_data = json.loads(sys.stdin.read())
        if not isinstance(input_data, dict):
            return
        transcript_path = input_data.get("transcript_path", "")
        trigger = str(input_data.get("trigger", "unknown"))  # "manual" or "auto"

        backup_path = None
        if args.backup and transcript_path:
            backup_path = backup_transcript(transcript_path, trigger)
        log_pre_compact(input_data, backup_path)

        if args.verbose:
            message = f"Compaction ({trigger}) starting."
            if backup_path:
                message += f" Transcript backed up to: {backup_path}"
            print(message)
    except Exception:
        pass


if __name__ == "__main__":
    main()
    sys.exit(0)
