#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.8"
# dependencies = []
# ///
# gingugu-init:managed-file - regenerated by `gingugu harness`; local edits are lost on --force

"""
PreToolUse Safety Gate

Blocks access to sensitive files (.env, credentials, secrets, .pem, .key,
SSH private keys) and prevents catastrophic rm commands. Everything else
passes. Any internal failure also passes: a broken guard must not stall a
session.
"""

import json
import os
import re
import sys
from datetime import datetime


def log_decision(input_data: dict, decision: str) -> None:
    """Append the tool, the path it named and the decision to logs/pre_tool_use.jsonl.

    Never the content or the command: a blocked write to .env carries the very
    secret this guard exists to keep off disk.
    """
    try:
        tool_input = input_data.get("tool_input")
        tool_input = tool_input if isinstance(tool_input, dict) else {}
        entry = {
            "session_id": input_data.get("session_id"),
            "tool_name": input_data.get("tool_name"),
            "decision": decision,
            "logged_at": datetime.now().isoformat(),
        }
        for key in ("file_path", "path"):
            if isinstance(tool_input.get(key), str):
                entry[key] = tool_input[key]
        project = os.environ.get("CLAUDE_PROJECT_DIR") or os.getcwd()
        log_dir = os.path.join(project, "logs")
        os.makedirs(log_dir, exist_ok=True)
        with open(os.path.join(log_dir, "pre_tool_use.jsonl"), "a") as f:
            f.write(json.dumps(entry) + "\n")
    except Exception:
        pass  # Silent failure


# ls, find and git may name a sensitive file without reading it - but only as a
# lone command. `ls; cat .env` is a read.
_LONE_SAFE_COMMAND = re.compile(r"^(ls|find|git)\s[^;&|`$()<>\n]*$")


def is_dangerous_rm_command(command):
    """Block only *catastrophic* recursive deletes, not every ``rm -rf``.

    A recursive rm is dangerous when its target is the filesystem root, the
    home dir, the parent/current dir, or a bare wildcard. Named targets like
    ``rm -rf dist`` / ``rm -rf build node_modules`` are ordinary cleanup and
    pass through. Non-recursive ``rm`` is never blocked here.
    """
    # Exact operands that must never be recursively deleted.
    catastrophic = {
        "/", "/*",
        "~", "~/", "~/*",
        "$HOME", "$HOME/", "$HOME/*", "${HOME}", "${HOME}/*",
        "..", "../", "../*",
        ".", "./", "./*",
        "*",
    }

    # Judge each command segment on its own: a `cd ~` elsewhere in the line
    # is not an operand of the rm.
    for segment in re.split(r"&&|\|\||[;|\n]", command):
        tokens = segment.split()
        while tokens and tokens[0] in ("sudo", "command", "exec", "nohup"):
            tokens = tokens[1:]
        if not tokens or not (tokens[0] == "rm" or tokens[0].endswith("/rm")):
            continue
        flags = [t for t in tokens[1:] if t.startswith("-")]
        recursive = any(
            f == "--recursive" or (not f.startswith("--") and re.search(r"[rR]", f))
            for f in flags
        )
        if not recursive:
            continue
        if any(t in catastrophic for t in tokens[1:] if not t.startswith("-")):
            return True

    return False


def names_private_ssh_key(text):
    """True if ``text`` names an SSH private key (``id_rsa``, ``id_ed25519_work``...).

    The ``.pub`` half of the pair is public by design - ``ssh-copy-id -i
    ~/.ssh/id_ed25519.pub`` must pass - so only names without it count.
    """
    for name in re.findall(r"id_(?:rsa|ed25519|ecdsa|dsa)[\w.-]*", text):
        if not name.endswith(".pub"):
            return True
    return False


def is_sensitive_file_access(tool_name, tool_input):
    """
    Check if any tool is trying to access sensitive files.
    Blocks: .env, credentials, secrets, .pem, .key files, SSH private keys.
    """
    sensitive_patterns = [
        # An env file is one whose NAME starts with .env (.env, .env.local):
        # .env not glued to a letter, digit or dot. `app.env` is a systemd
        # EnvironmentFile, not a project env file; `\.env`, `{.env,}` and
        # `C:\x\.env` are still env files. Sample/example/template files pass.
        r"(?<![\w.])\.env\b(?!\.sample|\.example|\.template)",
        r"credentials\.(json|yaml|yml|xml|toml)",
        r"secrets?\.(json|yaml|yml|xml|toml)",
        # A key file named anywhere in the string (`cat a.key | base64`), not
        # only at its end. The \w before the dot keeps `jq '.key'` passing.
        r"\w\.pem\b",
        r"\w\.key\b",
    ]

    def sensitive(text):
        if names_private_ssh_key(text):
            return True
        return any(re.search(p, text, re.IGNORECASE) for p in sensitive_patterns)

    if tool_name in ["Read", "Edit", "MultiEdit", "Write"]:
        return sensitive(tool_input.get("file_path", ""))

    if tool_name == "Grep":  # Grep returns file contents, so it is a read
        return any(sensitive(str(tool_input.get(k) or "")) for k in ("path", "glob"))

    if tool_name == "Bash":
        command = tool_input.get("command", "")
        return sensitive(command) and not _LONE_SAFE_COMMAND.match(command.strip())

    return False


def main():
    try:
        input_data = json.load(sys.stdin)
        tool_name = input_data.get("tool_name", "")
        tool_input = input_data.get("tool_input", {})

        if is_sensitive_file_access(tool_name, tool_input):
            log_decision(input_data, "block")
            msg = (
                "BLOCKED: Access to sensitive files "
                "(.env, credentials, secrets, keys) "
                "is prohibited"
            )
            print(msg, file=sys.stderr)
            print(
                "Use .env.sample or .env.example for "
                "template files instead",
                file=sys.stderr,
            )
            sys.exit(2)

        if tool_name == "Bash":
            command = tool_input.get("command", "")
            if is_dangerous_rm_command(command):
                log_decision(input_data, "block")
                print(
                    "BLOCKED: Dangerous rm command "
                    "detected and prevented",
                    file=sys.stderr,
                )
                sys.exit(2)

        log_decision(input_data, "allow")
        sys.exit(0)

    except json.JSONDecodeError:
        sys.exit(0)
    except Exception:
        sys.exit(0)


if __name__ == "__main__":
    main()
