#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.11"
# dependencies = []
# ///
# gingugu-init:managed-file - regenerated by `gingugu init`; local edits are lost on --force
"""Gingugu SessionStart hook.

Injects the Gingugu memory startup contract into Claude Code's context at the
start of every fresh session (startup / clear / resume). This is what makes the
memory protocol *reliable*: unlike a rules file (which is not guaranteed to be
loaded into context), a SessionStart hook re-injects the contract every time.

The project namespace is derived from the working directory name, so this hook
is fully portable — drop it into any repo and it targets that repo's namespace.

Installed by `gingugu init`. Pure stdlib; never crashes (fails soft on any error).
"""

import json
import os
import sys
from pathlib import Path


def _beyond_crow(cwd):
    """What the contract loads after crow: MEMORY_PERSONA if set, then the repo.

    crow is shared by every persona; a persona's self lives in its own
    namespace. A malformed MEMORY_PERSONA is ignored, never pasted in.
    """
    import re

    def valid(name):
        return bool(re.fullmatch(r"[A-Za-z0-9][A-Za-z0-9._-]{0,63}", name)) and name != "crow"

    names = []
    persona = os.environ.get("MEMORY_PERSONA", "").strip()
    if valid(persona):
        names.append(persona)
    # The directory name is pasted into an instruction to the model: a hostile
    # clone name (quotes, newlines) is dropped, never pasted.
    project = Path(cwd).name
    if valid(project) and project not in names:
        names.append(project)
    return ",".join(names) or "crow"


def build_startup_contract(cwd: str) -> str:
    """Imperative Gingugu startup contract, injected fresh every session."""
    project = Path(cwd).name
    rest = _beyond_crow(cwd)
    return (
        "=== SESSION STARTUP CONTRACT (Gingugu memory protocol - do this FIRST) ===\n"
        "Before responding to the first user message, run these in parallel as your\n"
        "opening action. Non-negotiable:\n"
        f'  - mcp__gingugu__memory_context(namespace="crow,{rest}", task_hint=...)\n'
        "    # ONE call: shared crow + your persona + this repo, deduped. Use compact=true for a\n"
        "    # lighter payload; pull full bodies via memory_recall.\n"
        f'  - mcp__gingugu__memory_stats(namespace="crow,{rest}")\n'
        "    # Same namespace list as memory_context, in one call: global\n"
        "    # health once plus each namespace's own breakdown.\n"
        "Before asking for ANY secret/token/credential: mcp__gingugu__credential_list()\n"
        f'NAMESPACES: "crow,{rest}" is the floor, always - it is derived from\n'
        "cwd and MEMORY_PERSONA, so it is never a guess. Load any OTHER namespace\n"
        "only when the work actually reaches that repo, or when the user says the\n"
        "task spans it. Never "
        'because a directory is mounted: "Additional working directories" is a\n'
        "permission allowlist, not the workspace, and at startup nothing has\n"
        "happened yet to justify a wider load. A later memory_context call costs\n"
        "one call; a wrong one costs the session's whole orientation.\n"
        "Rules: do not skip; do not ask which repo you are in (cwd is the answer);\n"
        'if a namespace is missing, create it with memory_namespaces(action="create", name=...).\n'
        "Check memory_recall before asking anything answered in a prior session.\n"
        "=== END CONTRACT ==="
    )


def build_context(source: str, cwd: str) -> str:
    parts: list[str] = []

    # Contract only on a fresh context window, not mid-session compaction.
    if source in ("startup", "clear", "resume"):
        parts.append(build_startup_contract(cwd))
        parts.append("")

    # Preload the project's checked-in memory digest if present.
    memory_file = Path(cwd, ".ai", "memory.md")
    if memory_file.exists():
        try:
            content = memory_file.read_text().strip()
            if content:
                parts.append("--- Project Memory (.ai/memory.md) ---")
                parts.append(content[:2000])
        except OSError:
            pass

    return "\n".join(parts)


def main() -> None:
    try:
        input_data = json.loads(sys.stdin.read())
        source = input_data.get("source", "startup")
        cwd = input_data.get("cwd", os.getcwd())

        context = build_context(source, cwd)
        if context:
            print(
                json.dumps(
                    {
                        "hookSpecificOutput": {
                            "hookEventName": "SessionStart",
                            "additionalContext": context,
                        }
                    }
                )
            )
        sys.exit(0)
    except Exception:
        # A hook must never break the session.
        sys.exit(0)


if __name__ == "__main__":
    main()
