#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.11"
# dependencies = []
# ///
# gingugu-init:managed-file - regenerated by `gingugu init`; local edits are lost on --force
"""Gingugu SubagentStart hook: warm minions.

Injects the memories a fenced minion can read, ranked for the task it was
spawned with, before its first turn. The decision lives in the installed
`gingugu` package (`gingugu hook subagent`) so it can be unit-tested; this file
is only the doorway. Only agents whose agent file carries a MEMORY_GRANT get
anything.

Never blocks on failure. Any error exits 0 and the subagent starts as before.
"""

import json
import shutil
import subprocess
import sys


def main() -> None:
    try:
        raw = sys.stdin.read()
        payload = json.loads(raw or "{}")
        if not isinstance(payload, dict) or not payload.get("agent_type"):
            sys.exit(0)

        if shutil.which("gingugu") is None:
            sys.exit(0)

        result = subprocess.run(
            ["gingugu", "hook", "subagent"],
            input=raw,
            capture_output=True,
            text=True,
            timeout=15,
        )
        if result.returncode == 0 and result.stdout.strip():
            print(result.stdout.strip())
    except Exception:
        # A hook must never break the session.
        pass
    sys.exit(0)


if __name__ == "__main__":
    main()
