#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.11"
# dependencies = []
# ///
# gingugu-init:managed-file - regenerated by `gingugu init`; local edits are lost on --force
"""Gingugu UserPromptSubmit hook: involuntary recall.

Surfaces memories a prompt woke, without the agent asking for them. The
decision itself lives in the installed `gingugu` package (`gingugu hook
prompt`) so it can be unit-tested; this file is only the doorway.

It is a doorway with a purpose. Loading the package costs ~410ms and the
encoder another ~500ms, and roughly 44% of real prompts are too short to
retrieve anything anyway. Applying the length floor HERE, in pure stdlib,
means an acknowledgement costs bare interpreter startup and never pays for
either. Only a prompt long enough to carry a subject is handed on.

The floor is deliberately the only test done here: it is one number, easy to
keep in step, and conservative. Every other gate - the score bar, the margin,
the lexical requirement, per-session suppression - stays authoritative in the
package, where it is covered by tests.

Never blocks. Any failure exits 0 and the turn proceeds in silence.
"""

import json
import shutil
import subprocess
import sys

MIN_PROMPT_CHARS = 40


def main() -> None:
    try:
        raw = sys.stdin.read()
        payload = json.loads(raw or "{}")
        if not isinstance(payload, dict):
            sys.exit(0)

        prompt = (payload.get("prompt") or "").strip()
        if len(prompt) < MIN_PROMPT_CHARS:
            sys.exit(0)

        if shutil.which("gingugu") is None:
            sys.exit(0)

        result = subprocess.run(
            ["gingugu", "hook", "prompt"],
            input=raw,
            capture_output=True,
            text=True,
            timeout=20,
        )
        if result.returncode == 0 and result.stdout.strip():
            print(result.stdout.strip())
    except Exception:
        # A hook must never break the session.
        pass
    sys.exit(0)


if __name__ == "__main__":
    main()
