"""Generate a labelled template-family probe set from a real brain.

WHY THIS EXISTS. Hand-labelling is what kept ``bench/local/brain-v1.json`` at
30 questions, and 30 binary questions means one question is worth 0.033 - so a
"+0.050 recall@1" result is one and a half questions and indistinguishable from
noise. That is not a hypothetical: a retrieval change measured on that set
looked like a strict Pareto improvement and, on a set generated by this module,
turned out to halve recall@1.

This sidesteps the labelling cost without giving up label quality, because the
labels here are **objectively verifiable rather than judged**:

    a phrase occurring in exactly ONE memory of a namespace has exactly ONE
    correct answer, and a scan can prove it.

No human decides what the right answer is, so the set can be large and still
trustworthy. Every candidate is re-verified against the corpus before it is
emitted, and dropped if the phrase turns out not to be unique.

WHAT IT TARGETS. Questions are drawn only from TEMPLATE FAMILIES - groups of
``MIN_FAMILY`` or more memories in one namespace sharing a title shape. That is
the corpus structure behind the top board item, and a real brain accumulates it
naturally (session handoffs, board snapshots, reflections).

QUERY SHAPE. Every query is ``what did we say about <phrase>``. The wrapper is
deliberate and fixed. Those stopwords are what ``build_match_query``'s OR-join
uses to pull the whole family into the candidate pool, which is the
precondition for the defect - a bare phrase would not reproduce it. Using one
wrapper everywhere keeps it a controlled variable rather than a source of
variance between questions.

POSITION. Each target is probed up to three times, with a phrase from its head,
middle and tail, and the question's ``kind`` names which. The embedder reads only
the first 512 tokens and truncates the rest silently, so a set that asks only
about openings cannot see that defect: measured 2026-09-27 on the real brain,
79.1% of memories ran past the window, yet every first-unique-phrase probe sat
inside it (median token 77), and probing the same targets from their tail cut
mrr from 0.3353 to 0.2078. Read the per-kind rows, not only the overall mean.
The ``head`` phrase is the original first-unique-phrase rule, so ``head``
figures stay comparable with numbers recorded before stratification.

READ THE OUTPUT'S LIMITS. The phrase is unique as a contiguous STRING, but FTS5
indexes WORDS, and the individual words of a phrase are usually common. So
these questions test phrase-level recall against a word-level index. That is a
real and important query shape ("I remember this wording, find the memory"),
but it is harder than "find the document with this rare token" and the absolute
numbers should be read with that in mind. A before/after comparison is
unaffected: both arms face the identical handicap.

DEPRECATED MEMORIES ARE NOT VALID ANSWERS, and they play two different roles
here. ``search()`` filters ``confidence != 'deprecated'`` unless the caller asks
for them, so a deprecated target is a question the engine is CORRECT to fail -
an unwinnable label that scores zero at every cutoff. Measured 2026-09-21: 11 of
135 questions were labelled this way and all 11 scored zero at recall@10, holding
the reported recall@1 down to 0.2074 where the corrected 126-question set
measures 0.2143. They are therefore excluded from families and from targets. They
remain in the SIBLING scan, where they are still evidence: a phrase shared with a
deprecated memory is not unique, and dropping them from that scan would
manufacture wrong labels - a far worse defect than the one this exclusion fixes.

The generated dataset contains real memory content and belongs under
``bench/local/`` (gitignored), never in the repository.
"""

from __future__ import annotations

import json
import re
import sqlite3
from collections import defaultdict
from pathlib import Path

# A family needs enough members that "which sibling" is a real question.
MIN_FAMILY = 3
# Capped per family so one 55-member family cannot dominate the metric.
QUESTIONS_PER_FAMILY = 3
# Tried longest-first: a longer phrase is more distinctive and more likely to
# be unique on the first try, but short ones still find targets in terse rows.
NGRAM_LENS = (5, 6, 4)
SIG_TOKENS = 3
WRAPPER = "what did we say about {}"

# Where in a memory each probe's phrase is taken from, and the question `kind`
# that labels it. The embedder silently truncates at 512 tokens and most of a
# real brain is longer, so a set probing only the opening cannot see that defect
# at all: measured 2026-09-27, every first-unique-phrase probe sat inside the
# window. Each value is an anchor as a fraction of the memory's length in words.
POSITIONS: dict[str, float] = {"head": 0.0, "middle": 0.5, "tail": 1.0}

# Stripped before computing a title signature. These are exactly the parts that
# DISTINGUISH members of a family (the date, the sail number, the item count),
# so removing them is what makes siblings collapse onto one signature.
_DATE = re.compile(r"\d{4}-\d{2}-\d{2}")
_PARENS = re.compile(r"\([^)]*\)")
_NUM = re.compile(r"\b\d+\w*\b")
_NONWORD = re.compile(r"[^\w\s]+")
_WS = re.compile(r"\s+")

_STOP = frozenset("""the a an and or but is was are were be been to of in on at for with that
    this it as by from not no so if then than we i my our its has had have do
    does did will would can could one two all any what which""".split())


def signature(title: str) -> str:
    """The title shape a family shares, with the distinguishing parts removed."""
    text = _NONWORD.sub(" ", _NUM.sub(" ", _PARENS.sub(" ", _DATE.sub(" ", title))))
    return " ".join(w.lower() for w in _WS.sub(" ", text).strip().split()[:SIG_TOKENS])


def content_ngrams(content: str, n: int) -> list[str]:
    """Word n-grams that can serve as a query phrase.

    Grams carrying punctuation are skipped: a phrase has to survive both FTS5
    tokenization and a literal substring check, and quotes or backticks are a
    needless way to make those two disagree. Grams that are all stopwords, or
    carry fewer than two content words, are skipped because they cannot
    identify anything.
    """
    return [gram for _, gram in _indexed_ngrams(content.split(), n)]


def _indexed_ngrams(words: list[str], n: int) -> list[tuple[int, str]]:
    """``content_ngrams`` with each gram's starting word index."""
    out: list[tuple[int, str]] = []
    for i in range(len(words) - n + 1):
        gram = words[i : i + n]
        if any(not w.replace("-", "").isalnum() for w in gram):
            continue
        lowered = [w.lower() for w in gram]
        if sum(1 for w in lowered if w not in _STOP) < 2:
            continue
        out.append((i, " ".join(gram)))
    return out


def find_families(rows: list[sqlite3.Row]) -> dict[tuple[str, str], list[sqlite3.Row]]:
    """Group memories into (namespace, title signature) families of MIN_FAMILY+.

    A one-token signature is rejected: it collides far too broadly to describe
    a template, and would manufacture families that do not exist.
    """
    families: dict[tuple[str, str], list[sqlite3.Row]] = defaultdict(list)
    for row in rows:
        sig = signature(row["title"])
        if len(sig.split()) >= 2:
            families[(row["ns"], sig)].append(row)
    return {key: members for key, members in families.items() if len(members) >= MIN_FAMILY}


def unique_phrase(
    memory: sqlite3.Row, siblings: list[sqlite3.Row], anchor: float = 0.0
) -> str | None:
    """A phrase from ``memory`` that appears in no other row of its namespace.

    THE LABEL PROOF. Every row of the namespace is checked, never a sample:
    a phrase that is unique among a family's siblings but shared with some
    unrelated memory would make the labelled answer simply wrong, and a wrong
    label is worse than a missing question.

    ``anchor`` is where in the memory to look, as a fraction of its length in
    words: the unique gram starting nearest it wins, earlier on a tie. The
    default of 0.0 is the original first-unique-phrase rule, unchanged.
    """
    words = memory["content"].split()
    target = anchor * max(len(words) - 1, 0)
    for n in NGRAM_LENS:
        grams = sorted(_indexed_ngrams(words, n), key=lambda ig: (abs(ig[0] - target), ig[0]))
        for _, gram in grams:
            needle = gram.lower()
            holders = [other["id"] for other in siblings if needle in other["content"].lower()]
            if holders == [memory["id"]]:
                return gram
    return None


def generate(conn: sqlite3.Connection) -> dict:
    """Build the probe dataset. ``conn`` should be opened read-only."""
    rows = conn.execute(
        "SELECT m.id, m.title, m.content, m.confidence, n.name AS ns "
        "FROM memories m JOIN namespaces n ON n.id = m.namespace_id"
    ).fetchall()

    # EVERY row, deprecated included, is a sibling for the uniqueness proof.
    by_namespace: dict[str, list[sqlite3.Row]] = defaultdict(list)
    for row in rows:
        by_namespace[row["ns"]].append(row)

    # Only retrievable rows can be answers - or can flatten a retrieval contest,
    # which is what family size is a proxy for. A deprecated sibling never
    # enters the candidate pool, so it competes with nothing.
    answerable = [row for row in rows if row["confidence"] != "deprecated"]

    questions: list[dict] = []
    # Largest families first: they are the hardest cases and the ones the
    # defect is actually about, so they should never be the ones truncated.
    families = sorted(find_families(answerable).items(), key=lambda kv: (-len(kv[1]), kv[0]))
    for (namespace, sig), members in families:
        made = 0
        for memory in members:
            if made >= QUESTIONS_PER_FAMILY:
                break
            # A phrase already asked for this target is dropped, not repeated:
            # a short memory may have one distinguishing sentence, and asking it
            # three times would triple-weight that target in the aggregate.
            asked: set[str] = set()
            for position, anchor in POSITIONS.items():
                phrase = unique_phrase(memory, by_namespace[namespace], anchor)
                if phrase is None or phrase in asked:
                    continue
                asked.add(phrase)
                questions.append(
                    {
                        "id": f"tf-{len(questions):04d}",
                        "query": WRAPPER.format(phrase),
                        "namespaces": [namespace],
                        "relevant": [memory["id"]],
                        "kind": position,
                        "notes": f"family={sig!r} size={len(members)} ns={namespace}",
                    }
                )
            made += bool(asked)

    return {
        "version": 1,
        "name": "real-brain-template-families",
        "description": (
            "GENERATED, not hand-labelled. Every question asks for a phrase occurring "
            "in exactly one memory of its namespace, verified against the corpus at "
            "generation time, and every target sits inside a template family of "
            f"{MIN_FAMILY}+ siblings sharing a title shape. Each target is probed "
            "at its head, middle and tail, and `kind` names the position; a "
            "position with no phrase of its own is dropped. Targets are always "
            "retrievable: deprecated memories are excluded as answers, since search "
            "withholds them by default, but are still scanned when proving a phrase "
            "unique. Contains real memory content: keep under bench/local/, never "
            "commit."
        ),
        "questions": questions,
    }


def write(dataset: dict, out: Path) -> None:
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(dataset, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
